### ISSUE TITLE
Give permission for public repos but not for private ones

### ISSUE THREAD

**Issue by rocboronat** [walkmod/walkmod-core#53]
Hi team!

I'm really interested in try walkmod with my public repos. But I've noticed that it asks for private repos privileges.

There's any chance of asking only for public ones?

Thanks for your work!

**Comment by rpau** [comment]
Hi,

Are you talking about walkmodhub right? If this is the case, don't worry, walkmodhub doesn't store any private info of your projects. It is only to allow that other users could execute it for private projects.

Anyway, walkmodhub only executes walkmod when you have your projects already configured locally and they contain the walkmod.xml file inside. So, you can see the results first locally, and then decide if you want to continue maintaining the automatic fixing with walkmodhub.

**Comment by rocboronat** [comment]
Hi! Yes, I think so (but I'm not too sure). I arrived here thanks a link of @rubenaranamorera . I've seen your landing website and tapped the "i want to receive PR's!" too fast :·D

The issue is that I also work at private companies that requests me to not give access to their repos, 'cause are **really really really** closed :·D

BTW to clarificate the issue, I'm talking about this screen:

![image](https://cloud.githubusercontent.com/assets/456499/13669398/860189bc-e6c3-11e5-8ed2-49b7e1672cde.png)

Thanks for the **quick** answer!

**Comment by rpau** [comment]
yes,

This is the walkmodhub. Anyway, private repos are only your own user private repos, not the companies repos. However, if you have forked it, probably they appear.

But, as I have said, you need to configure your project first with the rules that you want to apply, defining the source directory and also how to resolve the classpath (if it is not maven or gradle). In order to understand how the tool works, follow the getting start guide :)

Now, I understand why people sign in to walkmodhub, but never pushes their walkmod configurations in their projects :)

**Comment by rocboronat** [comment]
@rpau thanks for your time. Really appreciated!

I just changed the organizations settings to hide the own projects, and went forward to try walkmod in an own repo.

Thanks again, and congratulations for the good work!
