### ISSUE TITLE
Maven sub projects not handled

### ISSUE THREAD

**Issue by rgilles** [walkmod/walkmod-core#66]
Hi,
I'm testing walkmod on a maven project. I want to apply a refactoring action. Therefore I'm following the documentation of walkmod-refactor-plugin and execute the following sequence of command:
```
walkmod add -DrefactoringConfigFile="src/main/walkmod/refactor/refactoring-methods.json" refactor:classes
walkmod apply
```
After the execution of the first command I get a bunch of `walkmod.xml` file created under each sub project.
What I notice is that only the root `walkmod.xml` contains the `transform` element. The others are just empty:
### Root file
```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd">
<walkmod>
    <modules>
        <module>parent</module>
        <module>lib</module>
        <module>feature</module>
        <module>itest</module>
    </modules>
    <transformation type="refactor:classes">
        <param name="refactoringConfigFile">src/main/walkmod/refactor/refactoring-methods.json</param>
    </transformation>
</walkmod>
```
### sub projects file
```
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD"  "http://www.walkmod.com/dtd/walkmod-1.1.dtd" >
<walkmod>
</walkmod>
```
When I run the `apply` command from the root project and nothing is transformed.
In order to get the transformation applied I must run the first command `add` in all the sub projects and then run the `apply` command from the root one.
It sounds like there is no transitivity of the root configuration.
Is this a bug or should I proceed differently?

Thanks in advance,
Romain

**Comment by rpau** [comment]
Hi Romain,



The transformation needs to be added (walkmod add) with the -R (recursively) flag, to add it into all the modules. Afterwards, you simply run walkmod apply. If you want to ask all the options of walkmod add (walkmod add --help)





Let me know if it has worked.





---- On mié, 10 may 2017 11:49:19 +0200 Romain Gilles &lt;notifications@github.com&gt; wrote ----




Hi,

 I'm testing walkmod on a maven project. I want to apply a refactoring action. Therefore I'm following the documentation of walkmod-refactor-plugin and execute the following sequence of command:


walkmod add -DrefactoringConfigFile="src/main/walkmod/refactor/refactoring-methods.json" refactor:classes walkmod apply 
After the execution of the first command I get a bunch of walkmod.xml file created under each sub project.

 What I notice is that only the root walkmod.xml contains the transform element. The others are just empty:


Root file

&lt;!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd"&gt; &lt;walkmod&gt; &lt;modules&gt; &lt;module&gt;parent&lt;/module&gt; &lt;module&gt;lib&lt;/module&gt; &lt;module&gt;feature&lt;/module&gt; &lt;module&gt;itest&lt;/module&gt; &lt;/modules&gt; &lt;transformation type="refactor:classes"&gt; &lt;param name="refactoringConfigFile"&gt;src/main/walkmod/refactor/refactoring-methods.json&lt;/param&gt; &lt;/transformation&gt; &lt;/walkmod&gt; 
sub projects file

&lt;!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.1.dtd" &gt; &lt;walkmod&gt; &lt;/walkmod&gt; 
When I run the apply command from the root project and nothing is transformed.

 In order to get the transformation applied I must run the first command add in all the sub projects and then run the apply command from the root one.

 It sounds like there is no transitivity of the root configuration.

 Is this a bug or should I proceed differently?


Thanks in advance,

 Romain

**Comment by rgilles** [comment]
Sorry I did see it as it show the option is the reverse order that what I'm use to see:
```
--recursive, -R
```
Instead of 
```
-R, --recursive
```
Again thank you and sorry to disturb you with this stupid issue.
